In [ ]:
import numpy as np

**ndarray** <br>
The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.


Every item in an ndarray takes the same size of block in the memory. Each element in ndarray is an object of data-type object (called dtype).

**Syntax :** numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

**object :** Any object exposing the array interface method returns an array, or any (nested) sequence.

**dtype :** Desired data type of array, optional

**copy :** Optional. By default (true), the object is copied

**order :** C (row major) or F (column major) or A (any) (default)

**subok :** By default, returned array forced to be a base class array. If true, sub-classes passed through

**ndmin :** Specifies minimum dimensions of resultant array

In [ ]:
arr = np.array([i for i in range(1,11)])
print(arr)
print('Type : {}'.format(type(arr)))

[ 1  2  3  4  5  6  7  8  9 10]
Type : <class 'numpy.ndarray'>


In [ ]:
arr2D = np.array([[i for i in range(1,4)] for j in range(1,4)])
print(arr2D)
print("Dimension : {}".format(np.ndim(arr2D)))

#Access Elements
print(arr2D[0,2])
print(arr2D.shape)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
Dimension : 2
3
(3, 3)


In [ ]:
arr3D = np.array([[[i for i in range(1,4)] for j in range(1,4)] for x in range(1,4)])
print(arr3D)
print("Dimension : {}".format(np.ndim(arr3D)))
print(arr3D[0,2,1])

#shape property tells how many elements are there in the array
print("Shape : {}".format(arr3D.shape))
print("Size : {}".format(arr3D.size))

[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]
Dimension : 3
2
Shape : (3, 3, 3)
Size : 27


In [ ]:
arr2d = np.array([1,2,3,4,5], ndmin = 2)
print(arr2d)

[[1 2 3 4 5]]


In [ ]:
print("Shape : {}".format(arr2d.shape))
print("Size : {}".format(arr2d.size))

Shape : (1, 5)
Size : 5


In [ ]:
arrComplex = np.array([1,2,3,4,5], dtype = complex)
print(arrComplex)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


**NumPy supports a much greater variety of numerical types than Python does.**

[Numpy Datatypes descriptions](https://www.tutorialspoint.com/numpy/numpy_data_types.htm)

**Syntax :** numpy.dtype(object, align, copy)

**Object −** To be converted to data type object

**Align −** If true, adds padding to the field to make it similar to C-struct

**Copy −** Makes a new copy of dtype object. If false, the result is reference to builtin data type object

In [ ]:
print(np.dtype(np.int32)) 

int32


In [ ]:
print(np.dtype('complex64'))

complex64


In [ ]:
print(np.dtype([('age',np.int8)])) 

[('age', 'i1')]


In [ ]:
dt = np.dtype([('age',np.int8)]) 
print(np.array([1, 2, 3, 4, 5], dtype = dt))

[(1,) (2,) (3,) (4,) (5,)]


**np.arange(start, end, size)**

In [ ]:
#np.arange()

print(np.arange(10))
print(np.arange(5,10))
print(np.arange(1,11,2))

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[1 3 5 7 9]


This function is similar to arange() function. In this function, instead of step size, the number of evenly spaced values between the interval is specified. 

**numpy.linspace(start, stop, num, endpoint, retstep, dtype)**

**start :** The starting value of the sequence

**stop :** The end value of the sequence, included in the sequence if endpoint set to true

**num :** The number of evenly spaced samples to be generated. Default is 50

**endpoint :** True by default, hence the stop value is included in the sequence. If false, it is not included

**retstep :** If true, returns samples and step between the consecutive numbers

**dtype :** Data type of output ndarray

In [ ]:
print(np.linspace(10,20,5))

[10.  12.5 15.  17.5 20. ]


In [ ]:
print(np.linspace(10,20, 5, endpoint = False))

[10. 12. 14. 16. 18.]


In [ ]:
print(np.linspace(1,2,5, retstep = True))

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


This function returns an ndarray object that contains the numbers that are evenly spaced on a log scale. Start and stop endpoints of the scale are indices of the base, usually 10.

**numpy.logspace(start, stop, num, endpoint, base, dtype)**

**start :** The starting point of the sequence is basestart

**stop :** The final value of sequence is basestop

**num :** The number of values between the range. Default is 50

**endpoint :** If true, stop is the last value in the range

**base :** Base of log space, default is 10

**dtype :** Data type of output array. If not given, it depends upon other input arguments

In [ ]:
print(np.logspace(1.0, 2.0, num = 10))

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [ ]:
print(np.logspace(1,10,num = 10, base = 2))

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


This function is similar to numpy.array except for the fact that it has fewer parameters. This routine is useful for converting Python sequence into ndarray. 

**numpy.asarray(a, dtype = None, order = None)**

In [ ]:
print(np.asarray([1,2,3,4]))
print(np.asarray([1,2,3,4], dtype = float))
print(np.asarray((1,2,3,4)))  

[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


This function interprets a buffer as one-dimensional array. Any object that exposes the buffer interface is used as parameter to return an ndarray.

**numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)**

This function builds an ndarray object from any iterable object. A new one-dimensional array is returned by this function.

**numpy.fromiter(iterable, dtype, count = -1)**

In [ ]:
print(np.fromiter(range(5), dtype = float)) 

[0. 1. 2. 3. 4.]


**Random Package**

In [ ]:
#np.random.permutation()

print(np.random.permutation(np.arange(10)))
print(np.random.permutation(np.arange(20,30)))

[2 3 7 1 5 6 9 8 4 0]
[22 25 24 29 28 26 27 20 21 23]


In [ ]:
#np.random.randint()

print(np.random.randint(10,20))

12


In [ ]:
#np.random.rand()

print(np.random.rand(10)) #uniform Distribution

[0.58204664 0.79526657 0.96452909 0.51334283 0.28628921 0.17936634
 0.02376374 0.94556214 0.40967626 0.11523034]


In [ ]:
#np.random.randn()

print(np.random.randn(10)) #Gausian Distribution

[-1.85191473  0.25611751  1.44756368 -0.41658483  0.18143817 -1.44738979
  1.33242006  0.13132517 -0.65252337  0.12690407]


In [ ]:
#creating 2D array using random package
print(np.random.rand(3,3))

[[0.1425332  0.62356185 0.40393162]
 [0.36944442 0.1067133  0.2741402 ]
 [0.39877065 0.42393678 0.16464236]]


**Reshaping Arrays**

In [ ]:
#Reshaping np arrays

arr1 = np.random.rand(100).reshape(5,20)
print("Shape : {}".format(arr1.shape))
print(arr1)

Shape : (5, 20)
[[0.22386831 0.41605565 0.63662467 0.76904837 0.4682062  0.0759362
  0.64876421 0.58071704 0.76716139 0.77126874 0.07632368 0.45824617
  0.24996188 0.48694199 0.62614375 0.34485324 0.2312674  0.96873011
  0.24902987 0.86836887]
 [0.15399447 0.54956406 0.32921952 0.62185282 0.11566402 0.47424711
  0.67301125 0.08843295 0.46495134 0.1371169  0.56601053 0.41337738
  0.6311886  0.82547741 0.26387469 0.27459714 0.01293987 0.40861917
  0.13969203 0.01396666]
 [0.54056528 0.65231764 0.48089073 0.86427084 0.86438259 0.22594255
  0.97489773 0.74061369 0.77846499 0.91321192 0.06966074 0.67698305
  0.30272664 0.71102626 0.33864939 0.4539776  0.34590466 0.12312188
  0.93094272 0.00989043]
 [0.26361829 0.29888188 0.05270654 0.3307968  0.43104033 0.7832714
  0.93330717 0.54065225 0.95246214 0.55068728 0.05866616 0.33817792
  0.19815741 0.69973087 0.14014654 0.51038663 0.15418842 0.12801393
  0.45001633 0.15128897]
 [0.85871518 0.21223269 0.52543101 0.48181796 0.7627565  0.82530039
  

In [ ]:
#Reshaping np arrays

arr2 = np.random.rand(5,2)
print("Shape : {}".format(arr2.shape))
print(arr2)

Shape : (5, 2)
[[0.7946414  0.90091805]
 [0.96534436 0.66660308]
 [0.80789089 0.76871477]
 [0.46995815 0.05686732]
 [0.19497202 0.86154144]]


In [ ]:
arr2 = arr2.reshape(2,5)
print("Shape : {}".format(arr2.shape))
print(arr2)

Shape : (2, 5)
[[0.7946414  0.90091805 0.96534436 0.66660308 0.80789089]
 [0.76871477 0.46995815 0.05686732 0.19497202 0.86154144]]


**Creating Arrays**

In [ ]:
#Creating np arrays with empty values

emp = np.empty([2,10], dtype = int)
print(emp)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [ ]:
#Creating np arrays with zero value

zr = np.zeros([2,10])
print("Before Reshaping : {}".format(zr))
print("Shape : {}".format(zr.shape))
print()
zr = zr.reshape(4,5)
print("After Reshaping : {}".format(zr))
print("Shape : {}".format(zr.shape))

Before Reshaping : [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Shape : (2, 10)

After Reshaping : [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Shape : (4, 5)


In [ ]:
#Creating np arrays with one value

one = np.ones([2,10])
print("Before Reshaping : {}".format(one))
print("Shape : {}".format(one.shape))
print()
one = one.reshape(4,5)
print("After Reshaping : {}".format(one))
print("Shape : {}".format(one.shape))

Before Reshaping : [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Shape : (2, 10)

After Reshaping : [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape : (4, 5)


**Slicing Indexes :** arr[start : stop : step]

In [ ]:
#Slicing in np arrays

arr1 = np.arange(10,25)

In [ ]:
print(arr1[slice(2,7,2)]) 

[12 14 16]


In [ ]:
arr2 = arr1[5:-2]

In [ ]:
print("Array 1 : {}".format(arr1))
print("Array 2 : {}".format(arr2))

Array 1 : [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Array 2 : [15 16 17 18 19 20 21 22]


In [ ]:
# If i change in arr2 then it also reflect in arr1,
# Because slicing provide us a view of array and both share same memory location.

arr2[5] = 100
print("Array 1 : {}".format(arr1))
print("Array 2 : {}".format(arr2))

Array 1 : [ 10  11  12  13  14  15  16  17  18  19 100  21  22  23  24]
Array 2 : [ 15  16  17  18  19 100  21  22]


In [ ]:
# If we copy array while slicing then use copy()
arr2 = arr1[5:-2].copy()

In [ ]:
print(arr2)

[ 15  16  17  18  19 100  21  22]


In [ ]:
print(arr1[::3])

[10 13 16 19 22]


In [ ]:
print(arr1[::-3])

[24 21 18 15 12]


In [ ]:
#find index of particular element from index

idx = np.argwhere(arr1 == 15)[0][0]
print(idx)

5


In [ ]:
arr2D = np.round(10 * np.random.rand(5,5))

In [ ]:
print(arr2D)

[[ 6.  0.  6.  6.  1.]
 [ 1.  9. 10.  6.  4.]
 [ 5.  4.  3.  4.  8.]
 [10.  8.  6.  6.  0.]
 [ 8.  8.  7.  5.  9.]]


In [ ]:
print(arr2D[2,3])

4.0


In [ ]:
#If we want to accesss whole 2nd row
print(arr2D[2,:])

[5. 4. 3. 4. 8.]


In [ ]:
#If we want to accesss whole 2nd column
print(arr2D[ : ,2])

[ 6. 10.  3.  6.  7.]


In [ ]:
#If we just accessing sub matrix| then
print(arr2D[2:4, 2:4])

[[3. 4.]
 [6. 6.]]


In [ ]:
#Transposing the Matrix
arr2D.T

array([[ 6.,  1.,  5., 10.,  8.],
       [ 0.,  9.,  4.,  8.,  8.],
       [ 6., 10.,  3.,  6.,  7.],
       [ 6.,  6.,  4.,  6.,  5.],
       [ 1.,  4.,  8.,  0.,  9.]])

**Broadcasting**

Broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.



In [ ]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print(c)

[ 10  40  90 160]
