In [1]:
import numpy as np

In [2]:
oneD = np.array([1,2,3,4,5]) #create 1-D array using numpy
print(oneD)
type(oneD)

[1 2 3 4 5]


numpy.ndarray

In [3]:
twoD = np.array([[1,2,3],[4,5,6]]) #create 2-D array using numpy
print(twoD)
type(twoD)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [4]:
#create array using nrange
nArray = np.arange(0,10,2) #arange(start,stop,step)
print(nArray)
type(nArray)

[0 2 4 6 8]


numpy.ndarray

In [5]:
#create arrays zeros 
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#create arrays ones 
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
#create random arrays 
np.random.rand(1,10)

array([[0.85896466, 0.401787  , 0.11463846, 0.91860341, 0.9201139 ,
        0.1597908 , 0.39324922, 0.54484679, 0.82341869, 0.5432702 ]])

In [8]:
#normal distribution
np.random.randn(5,5)

array([[ 0.50024304,  0.624126  ,  1.08757573,  1.33518758, -1.06428903],
       [-0.30140691, -0.15851151, -0.28104977, -0.46058786, -1.5124204 ],
       [-1.72905178, -2.03929253, -0.64446227, -1.80019586, -0.64243576],
       [-1.19295331,  1.45272099, -3.99107495, -1.93616576,  1.85685504],
       [-0.29368609, -0.05313083,  0.1480168 ,  0.14775473,  0.30026281]])

In [9]:
np.random.randint(10,20,5)  #randint(start,stop,number)

array([13, 10, 18, 17, 13])

In [10]:
np.linspace(0,10,10) #linspace(start,stop,numberOfSamples)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [11]:
np.logspace(0,10,10,base=10.0)

array([1.00000000e+00, 1.29154967e+01, 1.66810054e+02, 2.15443469e+03,
       2.78255940e+04, 3.59381366e+05, 4.64158883e+06, 5.99484250e+07,
       7.74263683e+08, 1.00000000e+10])